services:
  - type: web
    name: be-board01
    env: java
    region: oregon
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -Dserver.port=$PORT -jar build/libs/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: GRADLE_OPTS
        value: "-Dorg.gradle.daemon=false"
