services:
  - type: web
    name: be-board01
    env: java
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/be_board01-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
